services:
  - type: web
    name: lil-movements-web
    env: node
    buildCommand: npm install && npm run migrate:deploy && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        fromDatabase:
          name: lil-movements-secrets
          property: nextauth_secret
      - key: NEXTAUTH_URL
        value: https://lil-movements-web.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: lil-movements-db
          property: connectionString

databases:
  - name: lil-movements-db
    databaseName: lilmovements
    user: lilmovements